// <auto-generated />
using System;
using Comandas_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comandas_API.Migrations
{
    [DbContext(typeof(ComandaDbContext))]
    [Migration("20251118230434_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("Comandas_API.Models.CardapioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaCardapioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiPreparo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCardapioId");

                    b.ToTable("CardapioItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Salgadinho frito em formato de gota, recheado com frango desfiado e temperado.",
                            PossuiPreparo = false,
                            Preco = 5.00m,
                            Titulo = "Coxinha"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Massa fina e crocante, recheada com carne moída, queijo ou outros ingredientes, frita até dourar.",
                            PossuiPreparo = false,
                            Preco = 6.50m,
                            Titulo = "Pastel"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Doce feito com leite condensado, chocolate em pó, manteiga e granulado de chocolate.",
                            PossuiPreparo = false,
                            Preco = 3.00m,
                            Titulo = "Brigadeiro"
                        });
                });

            modelBuilder.Entity("Comandas_API.Models.CategoriaCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriaCardapio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Salgados"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Doces"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Bebidas"
                        });
                });

            modelBuilder.Entity("Comandas_API.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Comandas_API.Models.ComandaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardapioItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("ComandaItem");
                });

            modelBuilder.Entity("Comandas_API.Models.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SituacaoMesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mesa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumeroMesa = 10,
                            SituacaoMesa = 0
                        },
                        new
                        {
                            Id = 2,
                            NumeroMesa = 11,
                            SituacaoMesa = 1
                        },
                        new
                        {
                            Id = 3,
                            NumeroMesa = 12,
                            SituacaoMesa = 2
                        });
                });

            modelBuilder.Entity("Comandas_API.Models.PedidoCozinha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("PedidoCozinha");
                });

            modelBuilder.Entity("Comandas_API.Models.PedidoCozinhaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComandaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoCozinhaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComandaItemId");

                    b.HasIndex("PedidoCozinhaId");

                    b.ToTable("PedidoCozinhaItem");
                });

            modelBuilder.Entity("Comandas_API.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Comandas_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.com",
                            Nome = "Admin",
                            Senha = "admin123"
                        });
                });

            modelBuilder.Entity("Comandas_API.Models.CardapioItem", b =>
                {
                    b.HasOne("Comandas_API.Models.CategoriaCardapio", "CategoriaCardapio")
                        .WithMany("Itens")
                        .HasForeignKey("CategoriaCardapioId");

                    b.Navigation("CategoriaCardapio");
                });

            modelBuilder.Entity("Comandas_API.Models.ComandaItem", b =>
                {
                    b.HasOne("Comandas_API.Models.Comanda", "Comanda")
                        .WithMany("Itens")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas_API.Models.PedidoCozinha", b =>
                {
                    b.HasOne("Comandas_API.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Comandas_API.Models.PedidoCozinhaItem", b =>
                {
                    b.HasOne("Comandas_API.Models.ComandaItem", "ComandaItem")
                        .WithMany()
                        .HasForeignKey("ComandaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Comandas_API.Models.PedidoCozinha", "PedidoCozinha")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCozinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComandaItem");

                    b.Navigation("PedidoCozinha");
                });

            modelBuilder.Entity("Comandas_API.Models.CategoriaCardapio", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Comandas_API.Models.Comanda", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Comandas_API.Models.PedidoCozinha", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
